baseurl = "https://brohde.me/"
relativeURLs = false
canonifyURLs = true
DefaultContentLanguage = "en"
title = "Bradin Rohde"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Cybersecurity x Mechanical Engineering"
  mainSections = ["blog"]
  logo = "assets/img/AboutPics/Bradin_Cropped.png" # Expecting square dimensions
  favicon = "assets/img/AboutPics/Bradin_Cropped.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
# disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employerâ€™s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Bradin Rohde"
  website = "https://brohde.me/"
  email = "bradinrohde0@gmail.com"
  #facebook = "username"
  github = "BrohdeXC"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  linkedin = "bradinrohde"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #medium = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"
  #lastfm = "username"
  #bluesky = "username"


[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

# ------------------
# ---- Courses -----
# ------------------
[[menu.main]]
    identifier = "courses"
    name = "Courses"
    weight = 3

# --- Password Cracking ---
[[menu.main]]
    parent = "courses"
    identifier = "passwordcracking"
    name = "Password Cracking"
    url = "/courses/passwordcracking/syllabus/"
    weight = 1

[[menu.main]]

# ------------------
# ---- Projects ----
# ------------------
[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "projects"
    name = "ShellFire"
    url = "/projects/shellfire/"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "PwnHound"
    url = "/projects/pwnhound/"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "1337ness"
    url = "/projects/1337ness/"
    weight = 3

[[menu.main]]
    parent = "projects"
    name = "HomeLab"
    url = "/projects/homelab"
    weight = 4

#[[menu.main]]
#    name = "Shop"
#    url = "https://brohde-engineering.square.site"
#    weight = "4"

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
